services:
  db:
    image: postgres:16
    environment: 
      POSTGRES_DB: microblog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgressql/data

  backend:
    build: .
    ports: 
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgressql+psycopg2://user:password@db:5432/microblog

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: unless-stopped

volumes:
  postgres_data: