"""added add ON DELETE CASCADE to all foreign keys

Revision ID: 8202a59773b7
Revises: ec3dcb378529
Create Date: 2025-09-30 15:20:24.371387

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8202a59773b7"
down_revision: Union[str, Sequence[str], None] = "ec3dcb378529"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("followers_following_id_fkey"), "followers", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("followers_follower_id_fkey"), "followers", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "followers", "users", ["follower_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "followers",
        "users",
        ["following_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("likes_user_id_fkey"), "likes", type_="foreignkey")
    op.drop_constraint(
        op.f("likes_tweet_id_fkey"), "likes", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "likes", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "likes", "tweets", ["tweet_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("media_tweet_id_fkey"), "media", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "media", "tweets", ["tweet_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("tweets_author_id_fkey"), "tweets", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "tweets", "users", ["author_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tweets", type_="foreignkey")
    op.create_foreign_key(
        op.f("tweets_author_id_fkey"), "tweets", "users", ["author_id"], ["id"]
    )
    op.drop_constraint(None, "media", type_="foreignkey")
    op.create_foreign_key(
        op.f("media_tweet_id_fkey"), "media", "tweets", ["tweet_id"], ["id"]
    )
    op.drop_constraint(None, "likes", type_="foreignkey")
    op.drop_constraint(None, "likes", type_="foreignkey")
    op.create_foreign_key(
        op.f("likes_tweet_id_fkey"), "likes", "tweets", ["tweet_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("likes_user_id_fkey"), "likes", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "followers", type_="foreignkey")
    op.drop_constraint(None, "followers", type_="foreignkey")
    op.create_foreign_key(
        op.f("followers_follower_id_fkey"),
        "followers",
        "users",
        ["follower_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("followers_following_id_fkey"),
        "followers",
        "users",
        ["following_id"],
        ["id"],
    )
    # ### end Alembic commands ###
