name: CI Pipeline

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-test:
    runs-on: ubuntu-latest
    environment: DB_DATA
    strategy:
      matrix:
        python-version: [3.13]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "TESTING=${{ secrets.TESTING }}" >> .env

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Check formatting with black
        run: black . -l 79 --check --diff

      - name: Check import order with isort
        run: isort . --check-only --diff --profile black

      - name: Run flake8
        run: flake8 . --exclude=./app/core/__init__.py,./app/schemas/__init__.py,./tests/__init__.py

      - name: Type check with mypy
        run: mypy app

      - name: Run tests with coverage
        run: |
          coverage run -m pytest -v
          coverage report --fail-under=90