name: Deploy to Production

on:
  release:
    types: [published]  

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: DOCKER_DATA
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU for multi-platform
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check Secrets Exist
        run: |
          echo "DOCKER_LOGIN is set: ${{ secrets.DOCKER_LOGIN != '' }}"
          echo "DOCKERHUB_TOKEN is set: ${{ secrets.DOCKERHUB_TOKEN != '' }}"
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from tag
        id: extract_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "Image version: ${{ env.VERSION }}"

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_LOGIN }}/microblog-backend:${{ env.VERSION }},${{ secrets.DOCKER_LOGIN }}/microblog-backend:latest

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/microblog
            docker compose down
            docker pull ${{ secrets.DOCKER_LOGIN }}/microblog-backend:${{ env.VERSION }}

            sed -i 's|image:.*backend.*|image: ${{ secrets.DOCKER_LOGIN }}/microblog-backend:${{ env.VERSION }}|' docker-compose.yml
            docker compose up -d --force-recreate
            echo "✅ Deployed version ${{ env.VERSION }} successfully!"